messages:
  phoneCraft: "&l&3Путем несложных махинаций Вы получили телефон, теперь Вы можете лично общаться с другими игрокам!\nЧтобы узнать подробности: /phone"
  alreadyCraftedPhone: "&l&6У вас уже есть телефон!"
  wrongSender: "This command can use only players!"
  noPhone: "&l&6У вас ещё нет телефона!"
  noNumber: "&l&6Такого номера не существует!"
  notEnoughMoney: "&l&6У вас недостаточно средств на телефоне!\nПополните его счет командой /phone pay"
  notEnoughArguments: "&l&6Недостаточно аргументов!"
  moneyIsRunningOut: "&l&6У вас заканчиваются средства на балансе! На следующее сообщение ужене хватит!\nПополните баланс командой /phone pay"
  changePhoneNumber: "&l&9Ваш номер был изменён: &1"
settings:
  messagePrice: 1