messages:
  phoneCraft: "&l&3Путем несложных махинаций Вы получили телефон, теперь Вы можете лично общаться с другими игрокам!\nЧтобы узнать подробности: /phone"
  alreadyCraftedPhone: "&l&6У вас уже есть телефон!"
  wrongSender: "This command can use only players!"
  notPhone: "&l&6У вас ещё нет телефона!"
  playerHasNotGotPhone: "&l&6У данного игрока нет телефона!"
  alreadySendAccept: "&l&6Вы уже отправили запрос на продажу телефона!"
  notNumber: "&l&6Такого номера не существует!"
  notPlayer: "&l&6Такого игрока не существует!"
  notPlayerOnline: "&l&6Игрок не в сети!"
  playerNotSell: "&l&6Данный игрок не продает Вам телефон!"
  notNumberAble: "&l&6Указана неправильная сумма!"
  notEnoughMoney: "&l&6У вас недостаточно средств на телефоне!\nПополните его счет командой /phonepay"
  notEnoughMoneyReal: "&l&6У вас недостаточно средств для оплаты!"
  notEnoughArguments: "&l&6Недостаточно аргументов!"
  moneyIsRunningOut: "&l&6У вас заканчиваются средства на балансе! На следующее сообщение ужене хватит!\nПополните баланс командой /phonepay"
  changePhoneNumber: "&l&9Ваш номер был изменён: &1"
  shouldGoFuck: "&l&6Похоже, здесь плохая связь, МТС подвёл :(\nПопробуйте отойти в другое место..."
  notEnoughSlots: "&l&6У вас недостаточно места в карманах! Очистите их и предложите продажу снова!"
  sellWasCancelled: "&l&6Покупка была отменена!"
settings:
  messagePrice: 1
  sellTimeInSec: 30
  hindranceRandom: 75