name: PLPhones
main: ru.prisonlife.plphones.Main
version: 1.0.0
author: rntsdkv
description: Plugin for phones on the server
depend: [PLCore]

commands:
  sms:
    description: Send SMS to player
    permission: plphones.sms
    usage: /sms <phone_number> <message>
  phone:
    description: Get information about SIM
    permission: plphones.phone.info
    usage: /phone
  sellsim:
    description: Sell your SIM to player
    permission: plphones.sellsim
    usage: /sellsim <player> <sum>
  phone pay:
    description: Put money on your SIM
    permission: plphones.phone.pay
    usage: /phone pay
  phone accept:
    description: Special command
    permission: plphones.phone.accept
    usage: /phone accept <player>